/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Conexion.ClienteImp;
import Personas.Cliente;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Conexion.ControlDatos;
import Personas.Persona;
/**
 *
 * @author Emanuel
 */
public class ListaClientes extends javax.swing.JDialog {
private String id;
private boolean fuecerrado=false;

    /**
     * Creates new form ListaClientes
     */
      public ListaClientes(java.awt.Frame parent, boolean modal) {
      super(parent, modal);
//      this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        initComponents();
        this.setLocationRelativeTo(null);
        this.ActualizarTabla();
    }

    public String getId() {
        return id;
    }
    
    public boolean mostrarVentana(){
        this.setVisible(true);
        return !fuecerrado;
    }
    
        /**
         * metodo actualizar tabla
         * llenado de la tabla
         */
    private void ActualizarTabla(){
        DefaultTableModel tabla = new DefaultTableModel();
        ClienteImp control = new ClienteImp();
        ArrayList<Persona> datos;
        String[] fila = new String[4];
        tabla.addColumn("ID");
        tabla.addColumn("Nombre");
        tabla.addColumn("Apellido");
        tabla.addColumn("Cédula");

        datos = control.LeerDatos();
        for (int f = 0; f < datos.size(); f++) {
            fila[0]=Integer.toString(datos.get(f).getid());
            fila[1] = datos.get(f).getnombre();
            fila[2] = datos.get(f).getApellido();
            fila[3] = Integer.toString(datos.get(f).getcedula());
            tabla.addRow(fila);
        }
        this.TablaClientes.setModel(tabla);

    }
        private void buscador(){
 DefaultTableModel tabla = new DefaultTableModel();
        ClienteImp control = new ClienteImp();
        ArrayList<Persona> datos;
        String[] fila = new String[4];
        tabla.addColumn("ID");
        tabla.addColumn("Nombre");
        tabla.addColumn("Apellido");
        tabla.addColumn("Cédula");

        datos = control.BuscarUsuario(this.BuscaNombre.getText());
        for (int f = 0; f < datos.size(); f++) {
            fila[0]=Integer.toString(datos.get(f).getid());
            fila[1] = datos.get(f).getnombre();
            fila[2] = datos.get(f).getApellido();
            fila[3] = Integer.toString(datos.get(f).getcedula());
            tabla.addRow(fila);
        }
        this.TablaClientes.setModel(tabla);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        BuscaNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Listado de clientes");

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Cedula"
            }
        ));
        jScrollPane1.setViewportView(TablaClientes);

        BuscaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaNombreActionPerformed(evt);
            }
        });
        BuscaNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscaNombreKeyReleased(evt);
            }
        });

        jLabel2.setText("Buscar nombre:");

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(aceptar)
                .addGap(36, 36, 36)
                .addComponent(Salir)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(Salir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * 
 * @param evt 
 * boton aceptar
 * guarda datos
 */
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        int fila=this.TablaClientes.getSelectedRow();
        if(fila<0) return;
      this.id=this.TablaClientes.getValueAt(fila, 0).toString();
        this.dispose();
    }//GEN-LAST:event_aceptarActionPerformed

    private void BuscaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaNombreActionPerformed
        // TODO add your handling code here:
        String nombre=BuscaNombre.getText();
    }//GEN-LAST:event_BuscaNombreActionPerformed
/**
 * boton salir
 * @param evt 
 */
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        fuecerrado=true;
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void BuscaNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscaNombreKeyReleased
        // TODO add your handling code here:
        buscador();
    }//GEN-LAST:event_BuscaNombreKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListaClientes dialog = new ListaClientes(new javax.swing.JFrame(),true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter(){
                @Override
                public void windowClosing(java.awt.event.WindowEvent e){
                System.exit(0);}
                });
               
                
//                new ListaClientes1().setVisible(true);
            }
        });
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ListaClientes2().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuscaNombre;
    private javax.swing.JButton Salir;
    private javax.swing.JTable TablaClientes;
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
